### ISSUE TITLE
Weird solid infill

### ISSUE THREAD

**Issue by coolxm** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#26]
dont know how to describe this
![image](https://user-images.githubusercontent.com/47038292/226854313-2babcd07-aa41-4b9d-a597-8e9a12f0ec11.png)

**Comment by 5axes** [comment]
Hilbert "Style" Infilll  : https://en.wikipedia.org/wiki/Hilbert_curve because unfortunatly it's not a Real Hilbert curve as you don't have just one start point.

**Comment by nicolai-wachenschwan** [comment]
The line errors occur, because the previous tool position gets deleted, when deleting the old solid infill.
Haven't had the time to fix this yet. If you have the time at spare I would be happy if you could contribute a bug fix via pull-request. 
The problem lies in the  prepareDeletion Method, starting at line 696 (current).

**Comment by ghylander** [comment]
Having this issue as well, have you had he time to look into it?
