### ISSUE TITLE
No supports made

### ISSUE THREAD

**Issue by sthompson-celerity** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#38]
This is the layer with bridging on it: 
before modification:
![image](https://user-images.githubusercontent.com/94012390/229152531-3a30030e-d3e3-409f-b189-6b82967bcb85.png)
after modification:
![image](https://user-images.githubusercontent.com/94012390/229150638-cf7c44ab-a502-4eb1-82f0-247c1154ec5c.png)
and you can see the next layer here:
![image](https://user-images.githubusercontent.com/94012390/229150936-7c8c8c6e-86e0-4e6c-850e-42acbfa0a6ce.png)

here is my output:
```
E:\Tools\Prusa3D\Utilities\arcs.py:1087: PrusaSlicer-Setting: Travel Moves may cross the outline and therefore cause artefacts in arc generation.
last read linenumber: 5239
layers: 18
E:\Tools\Prusa3D\Utilities\arcs.py:492: Layer 0: no height found, using layerheight default!
overhang found layer 11: 1
E:\Tools\Prusa3D\Utilities\arcs.py:529: Layer 10: No ExternalPerimeterPolys found in prev Layer
E:\Tools\Prusa3D\Utilities\arcs.py:166: Skipping Polygon because to StartLine Found
modifying GCode
oldpolys found in layer: 12
making hilbert surface
```

There is clearly something I am missing, but I dont know what it is...

**Comment by nicolai-wachenschwan** [comment]
Sorry for the late answer. The Problem is, that the geoemtry is special and not supported at the moment.
Detailed: The arcs shall be generated above very thin parts, therefore the arcs and the prev layers do not overlap enough. The algorithm cant find a startpoint.

Generally speaking the arcs are not good at classical bridging in a situation like this.
